// Termos de uso (só o servidor usa). Revisão jurídica das traduções recomendada: o texto em português é o original.
import type { Shape } from "../types";

const en = {
  metaTitle: "Terms of Use",
  breadcrumb: "Terms of Use",
  heading: "Terms of Use and Conditions of Service",
  sections: [
    {
      title: "1. Acceptance of the Terms",
      items: [
        'By creating an account and using the ResolveLabs tools, you (hereinafter "User") expressly agree to these Terms of Use. If you do not agree with any condition described here, use of the platform must be stopped immediately.',
      ],
    },
    {
      title: "2. Nature of the Services and Local (Client-Side) Processing",
      items: [
        "ResolveLabs provides technical and financial utility tools (such as PDF to OFX conversion, XML repair, among others).",
        "2.1. Privacy by Design: The processing, conversion and reading of sensitive files (statements, spreadsheets, documents) takes place exclusively in the User's browser. ResolveLabs does NOT upload, does NOT process on its servers and does NOT store the content of the files processed by these tools.",
        "2.2. The security of the local environment, including the absence of malware on the User's computer that could intercept data in the browser, is the User's sole responsibility.",
      ],
    },
    {
      title: "3. Disclaimer on Data Accuracy",
      items: [
        "The conversion and data extraction tools rely on common market patterns (e.g. bank PDF layouts). Since financial institutions may change the formatting of their documents without notice, ResolveLabs does not guarantee 100% accuracy in data extraction.",
        "3.1. It is the sole obligation of the User (or their accounting/finance department) to check the integrity, values and accuracy of the generated files (such as .ofx or .xml) before importing them into ERP, accounting or government systems.",
        "3.2. ResolveLabs disclaims any liability for fines, interest, delays, accounting inconsistencies or financial losses resulting from the use of files generated by the platform.",
      ],
    },
    {
      title: "4. Plans, Trial Period and Billing",
      items: [
        "4.1. Trial: ResolveLabs may offer a free trial period of 7 (seven) days to new users. Cancellation can be made at any time before the end of this period without charge.",
        "4.2. Recurring Subscription: After the trial period, the PRO plan will be activated automatically and the applicable amount will be charged monthly by credit card.",
        "4.3. Cancellation: The User may cancel the subscription at any time through the control panel. Access to the PRO plan will remain active until the end of the current billing cycle. We do not provide refunds or chargebacks for unused fractions of months.",
      ],
    },
    {
      title: "5. Acceptable Use and Affiliate Program",
      items: [
        "5.1. The User agrees not to use the ResolveLabs tools to process unlawful material or to circumvent government security measures.",
        '5.2. Affiliates: When taking part in the "Refer and Earn" program, the User may not use spam, malicious social engineering or create fake accounts (self-referral) to obtain advantages. Violating this rule will result in immediate banning of the account and loss of accumulated rewards.',
      ],
    },
    {
      title: "6. Collection of Registration Data",
      items: [
        "To provide the service and technical support, we store only the User's account data: Email, Mobile Phone Number and payment and access history. This data is not sold or shared with third parties for marketing purposes.",
        "6.1. Access records: for security, fraud prevention and service improvement, we record the pages visited and the tools used, together with the IP address, the approximate location derived from the IP, the browser and the device's system and, when logged in, the associated account. We never record the content or the name of the files processed in the browser. These records are deleted automatically after 180 days.",
      ],
    },
    {
      title: "7. Changes to the Terms and the Platform",
      items: [
        "ResolveLabs reserves the right to modify, suspend or discontinue any tool on the platform at any time. These Terms may be updated periodically, and continued use of the platform after the changes constitutes acceptance of the new terms.",
      ],
    },
    {
      title: "8. Jurisdiction",
      items: [
        "The courts of the district of the ResolveLabs developer's seat in Brazil are elected to settle any doubts or disputes arising from these Terms of Use, waiving any other, however privileged.",
      ],
    },
  ],
};

export type LegalMessages = Shape<typeof en>;

const es: LegalMessages = {
  metaTitle: "Términos de Uso",
  breadcrumb: "Términos de Uso",
  heading: "Términos de Uso y Condiciones del Servicio",
  sections: [
    {
      title: "1. Aceptación de los Términos",
      items: [
        'Al crear una cuenta y utilizar las herramientas de ResolveLabs, tú (en adelante "Usuario") aceptas expresamente estos Términos de Uso. Si no estás de acuerdo con alguna condición aquí descrita, debes dejar de usar la plataforma de inmediato.',
      ],
    },
    {
      title: "2. Naturaleza de los Servicios y Procesamiento Local (Client-Side)",
      items: [
        "ResolveLabs ofrece herramientas utilitarias técnicas y financieras (como conversión de PDF a OFX, reparación de XML, entre otras).",
        "2.1. Privacidad por Diseño: El procesamiento, la conversión y la lectura de archivos sensibles (extractos, hojas de cálculo, documentos) ocurre exclusivamente en el navegador del Usuario. ResolveLabs NO sube, NO procesa en sus servidores y NO almacena el contenido de los archivos procesados por estas herramientas.",
        "2.2. La seguridad del entorno local, incluida la ausencia de malware en el ordenador del Usuario que pueda interceptar datos en el navegador, es responsabilidad exclusiva del Usuario.",
      ],
    },
    {
      title: "3. Exención de Responsabilidad sobre la Precisión de los Datos",
      items: [
        "Las herramientas de conversión y extracción de datos se basan en patrones comunes del mercado (p. ej.: diseños de PDF bancarios). Como las instituciones financieras pueden cambiar el formato de sus documentos sin previo aviso, ResolveLabs no garantiza una precisión del 100% en la extracción de los datos.",
        "3.1. Es obligación exclusiva del Usuario (o de su departamento contable/financiero) comprobar la integridad, los valores y la exactitud de los archivos generados (como .ofx o .xml) antes de importarlos en sistemas ERP, contables o gubernamentales.",
        "3.2. ResolveLabs queda exento de cualquier responsabilidad por multas, intereses, retrasos, inconsistencias contables o perjuicios financieros derivados del uso de archivos generados por la plataforma.",
      ],
    },
    {
      title: "4. Planes, Período de Prueba (Trial) y Facturación",
      items: [
        "4.1. Prueba: ResolveLabs puede ofrecer un período de prueba gratuito de 7 (siete) días a nuevos usuarios. La cancelación puede hacerse en cualquier momento antes del fin de este período sin cargos.",
        "4.2. Suscripción Recurrente: Tras el período de prueba, el plan PRO se activará automáticamente y el importe aplicable se cobrará mensualmente con tarjeta de crédito.",
        "4.3. Cancelación: El Usuario puede cancelar la suscripción en cualquier momento desde el panel de control. El acceso al plan PRO seguirá activo hasta el final del ciclo de facturación actual. No realizamos reembolsos ni devoluciones por fracciones de meses no utilizadas.",
      ],
    },
    {
      title: "5. Uso Aceptable y Programa de Afiliados",
      items: [
        "5.1. El Usuario se compromete a no utilizar las herramientas de ResolveLabs para procesar material ilícito o eludir medidas de seguridad gubernamentales.",
        '5.2. Afiliados: Al participar en el programa "Recomienda y Gana", el Usuario no podrá utilizar prácticas de spam, ingeniería social maliciosa ni crear cuentas falsas (autorreferencia) para obtener ventajas. La infracción de esta regla resultará en el bloqueo inmediato de la cuenta y la pérdida de las recompensas acumuladas.',
      ],
    },
    {
      title: "6. Recopilación de Datos de Registro",
      items: [
        "Para la prestación del servicio y el soporte técnico, almacenamos solo los datos de cuenta del Usuario: Correo electrónico, Número de Móvil e historial de pagos y accesos. Estos datos no se venden ni se comparten con terceros con fines de marketing.",
        "6.1. Registros de acceso: por seguridad, prevención de fraudes y mejora del servicio, registramos las páginas visitadas y las herramientas utilizadas, junto con la dirección IP, la ubicación aproximada derivada de la IP, el navegador y el sistema del dispositivo y, cuando hay sesión iniciada, la cuenta asociada. Nunca registramos el contenido ni el nombre de los archivos procesados en el navegador. Estos registros se eliminan automáticamente después de 180 días.",
      ],
    },
    {
      title: "7. Modificaciones de los Términos y de la Plataforma",
      items: [
        "ResolveLabs se reserva el derecho de modificar, suspender o discontinuar cualquier herramienta de la plataforma en cualquier momento. Estos Términos pueden actualizarse periódicamente, y el uso continuado de la plataforma tras los cambios constituye la aceptación de los nuevos términos.",
      ],
    },
    {
      title: "8. Fuero",
      items: [
        "Se elige el fuero de la jurisdicción de la sede del desarrollador de ResolveLabs en Brasil para dirimir cualquier duda o controversia derivada de estos Términos de Uso, renunciando a cualquier otro por privilegiado que sea.",
      ],
    },
  ],
};

const pt: LegalMessages = {
  metaTitle: "Termos de Uso",
  breadcrumb: "Termos de Uso",
  heading: "Termos de Uso e Condições de Serviço",
  sections: [
    {
      title: "1. Aceitação dos Termos",
      items: [
        'Ao criar uma conta e utilizar as ferramentas do ResolveLabs, você (doravante "Usuário") concorda expressamente com estes Termos de Uso. Caso não concorde com qualquer condição aqui descrita, o uso da plataforma deve ser imediatamente interrompido.',
      ],
    },
    {
      title: "2. Natureza dos Serviços e Processamento Local (Client-Side)",
      items: [
        "O ResolveLabs fornece ferramentas utilitárias técnicas e financeiras (como conversão de PDF para OFX, reparo de XML, entre outros).",
        "2.1. Privacidade por Design: O processamento, conversão e leitura de arquivos sensíveis (extratos, planilhas, documentos) ocorre exclusivamente no navegador (browser) do Usuário. O ResolveLabs NÃO faz upload, NÃO processa em seus servidores e NÃO armazena os conteúdos dos arquivos processados por estas ferramentas.",
        "2.2. A segurança do ambiente local, incluindo a ausência de malwares no computador do Usuário que possam interceptar dados no navegador, é de exclusiva responsabilidade do Usuário.",
      ],
    },
    {
      title: "3. Isenção de Responsabilidade sobre Precisão de Dados",
      items: [
        "As ferramentas de conversão e extração de dados baseiam-se em padrões comuns de mercado (ex: layouts de PDFs bancários). Como instituições financeiras podem alterar a formatação de seus documentos sem aviso prévio, o ResolveLabs não garante 100% de precisão na extração dos dados.",
        "3.1. É obrigação exclusiva do Usuário (ou de seu departamento contábil/financeiro) conferir a integridade, os valores e a exatidão dos arquivos gerados (como .ofx ou .xml) antes de importá-los em sistemas ERP, contábeis ou governamentais.",
        "3.2. O ResolveLabs isenta-se de qualquer responsabilidade por multas, juros, atrasos, inconsistências contábeis ou prejuízos financeiros decorrentes do uso de arquivos gerados pela plataforma.",
      ],
    },
    {
      title: "4. Planos, Período de Teste (Trial) e Faturamento",
      items: [
        "4.1. Trial: O ResolveLabs pode oferecer um período de teste gratuito de 7 (sete) dias para novos usuários. O cancelamento pode ser feito a qualquer momento antes do término deste período sem cobranças.",
        "4.2. Assinatura Recorrente: Após o período de teste, o plano PRO será ativado automaticamente e o valor aplicável será cobrado mensalmente via cartão de crédito.",
        "4.3. Cancelamento: O Usuário pode cancelar a assinatura a qualquer momento através do painel de controle. O acesso ao plano PRO continuará ativo até o final do ciclo de faturamento atual. Não realizamos reembolsos ou estornos por frações de meses não utilizados.",
      ],
    },
    {
      title: "5. Uso Aceitável e Programa de Afiliados",
      items: [
        "5.1. O Usuário compromete-se a não utilizar as ferramentas do ResolveLabs para processar material ilícito ou contornar medidas de segurança governamentais.",
        '5.2. Afiliados: Ao participar do programa "Indique e Ganhe", o Usuário não poderá utilizar práticas de spam, engenharia social maliciosa ou criar contas falsas (auto-indicação) para obter vantagens. A violação desta regra resultará no banimento imediato da conta e perda das recompensas acumuladas.',
      ],
    },
    {
      title: "6. Coleta de Dados Cadastrais",
      items: [
        "Para a prestação do serviço e suporte técnico, armazenamos apenas os dados de conta do Usuário: E-mail, Número de Celular e histórico de pagamentos e acessos. Estes dados não são vendidos ou compartilhados com terceiros para fins de marketing.",
        "6.1. Registros de acesso: para segurança, prevenção de fraudes e melhoria do serviço, registramos as páginas acessadas e as ferramentas utilizadas, junto com o endereço IP, a localização aproximada derivada do IP, o navegador e o sistema do aparelho e, quando houver login, a conta associada. Nunca registramos o conteúdo nem o nome dos arquivos processados no navegador. Esses registros são apagados automaticamente após 180 dias.",
      ],
    },
    {
      title: "7. Modificações dos Termos e da Plataforma",
      items: [
        "O ResolveLabs reserva-se o direito de modificar, suspender ou descontinuar qualquer ferramenta da plataforma a qualquer momento. Estes Termos podem ser atualizados periodicamente, e o uso contínuo da plataforma após as alterações constitui aceitação dos novos termos.",
      ],
    },
    {
      title: "8. Foro",
      items: [
        "Fica eleito o foro da comarca da sede do desenvolvedor do ResolveLabs no Brasil, para dirimir quaisquer dúvidas ou controvérsias oriundas destes Termos de Uso, renunciando a qualquer outro por mais privilegiado que seja.",
      ],
    },
  ],
};

export default { en, es, pt };
